# Generated by Django 3.2.10 on 2022-03-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_table'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Product1',
        ),
        migrations.AlterModelOptions(
            name='product1',
            options={'ordering': ('name',), 'verbose_name': 'product1', 'verbose_name_plural': 'products1'},
        ),
    ]
